server:
  port: 9002
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.jerry.gulimall.order: debug

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://101.35.8.125:7001/eureka/
  instance:
    prefer-ip-address: true

